### ISSUE TITLE
BUGGY organization in your Youtube and github links is killing my time and user experience joy

### ISSUE THREAD

**Issue by richlysakowski** [avrabyt/YouTube-Tutorials#13]
Hi Avra, 

I appreciate your efforts in creating the videos with great demonstrations.  However, I cannot find the specific github.com code repo that I need for any single video without lots of hunting and digging and verifying the code against the video.  

When I watch a video, I need ONE AND ONLY ONE github.com link, not a link to one of your several "master" repos for your large collection of youtube videos or medium articles.   You have at least two github accounts, old and new, student or professional, sponsored or not sponsored.  Which is which? 

Please provide ONE github.com link at the top of your youtube video description -- for the code for that video only, ABOVE all the adlinks and sponsor links, so that we can find the video-specific code in one click.  

Thank you.  

Rich

**Comment by avrabyt** [comment]
Hi Rich! 

Thanks for your feedback, I do appreciate. Apologies for inconvenience. Please do let me know which exact code you are looking for , I'm happy to direct you to the repo.


> However, I cannot find the specific github.com code repo that I need for any single video without lots of hunting and digging and verifying the code against the video.


Mostly, I try my best to push all codes is one repo . For instance - [this](https://github.com/avrabyt/YouTube-Tutorials) is meant for it. In fact, there are few [submodules ](https://github.com/avrabyt/YouTube-Tutorials/commit/7e655021efdf0a467736915b32dc64f2b206e0c2) associated within this main branch, which is automated further with help of dependency bot to monitor any changes in the mother repo. Moreover, all my videos / blogs are automated and updated folder-wise in this same repo so that none of them gets missed/overlooked.



>not a link to one of your several "master" repos for your large collection of youtube videos or medium articles.

The  main repo is separated into several subfolders ! Over time, I would make it more organized whenever necessary. 



> You have at least two github accounts, old and new, student or professional, sponsored or not sponsored. Which is which?

Well, this is not entirely correct. I do have two Github accounts, that's right. But as far I can recollect that account isn't used for any of my open-source projects / videos / blogs . I would say, [THIS](https://github.com/avrabyt) is the one where you will find all my video/ blog related stuffs which perhaps you are interested about ! 





> When I watch a video, I need ONE AND ONLY ONE github.com link, not a link to one of your several "master" repos for your large collection of Youtube videos or medium articles. .....
> .... Please provide ONE github.com link at the top of your youtube video description -- for the code for that video only, ABOVE all the adlinks and sponsor links, so that we can find the video-specific code in one click.

In my typical workflow of creating videos/ blogs - briefly, starts with working on a certain project, documenting it in a form of a video and later push it as a blog post. And I do agree, in some cases, I need to wait a week to open-source the code un till I manage to publish the blog post hence in my video description I leave my main repo ( i.e. this one ) as a source, which over time _will be updated_ . **However, I do understand the drawback here, at the end of the day as an audience, all we care is a single link to click ( perhaps this repo with submodules will serve the best in future ) -  I'll def see what can be done best , thanks!** 

Curious, how helpful are the pinned comments underneath the video,  with link for the respective blog posts ? 
In that way, blog posts are associated with links / demo apps and codes. All in one-bundle. 

Nevertheless,  I promise in coming months once I finish my studies, I'll put all efforts to organize it better i.e.  a single repo with sub modules ( for each demo project / video ) . 

 **For time being , please don't hesitate to write to me about the code link you are looking for . Alternatively, you can leave your comment here or write to me over my email ( avrab.yt@gmail.com)** . Also, happy to know if you have any other suggestions / improvements on how to make it more accessible.

_Thanks, 
Avra_
